### ISSUE TITLE
Crashing when trying to lock a door.

### ISSUE THREAD

**Issue by luinbytes** [vassbo/DoorLock#1]
First mod run, I crafted a key, set a PW and rightclicked it and it crashes my server, tried a few times. Seems to be to do with hashing the pw's > <

`[19:24:53] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: org/apache/commons/codec/binary/Base64
        at net.vassbo.door_lock.util.KeyPass.getKeyHash(KeyPass.java:12) ~[door_lock-1.1-1.21.jar:?]
        at net.vassbo.door_lock.util.LockCheck.canOpen(LockCheck.java:76) ~[door_lock-1.1-1.21.jar:?]
        at net.minecraft.class_2323.handler$zhc000$door_lock$onUse(class_2323.java:564) ~[server-intermediary.jar:?]
        at net.minecraft.class_2323.method_55766(class_2323.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_55781(class_4970.java:1173) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:355) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1158) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:42) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:10) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.codec.binary.Base64
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 24 more`

**Comment by vassbo** [comment]
https://www.curseforge.com/minecraft/mc-mods/door-lock/files/5800656
